<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>9b98c976-0194-47da-973d-a16d20726862</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = concat('javascript:__doPostBack(' , &quot;'&quot; , 'ctl00$MainContent$ctl00$ucFormItems$ctl00$rgContacts$ctl00$ctl04$ctl00' , &quot;'&quot; , ',' , &quot;'&quot; , '' , &quot;'&quot; , ')') and (text() = 'Edit' or . = 'Edit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$MainContent$ctl00$ucFormItems$ctl00$rgContacts$ctl00$ctl04$ctl00','')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ctl00_ucFormItems_ctl00_rgContacts_ctl00__0&quot;)/td[7]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
