<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fx-contactfulladdnotesubmi</name>
   <tag></tag>
   <elementGuidId>4302c179-7026-4584-9248-919297af1506</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fx-contactfulladdnotesubmitbutton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_pnlInstructions&quot;)/div[@class=&quot;fx-contactfulladdnotesubmit&quot;]/div[@class=&quot;fx-contactfulladdnotesubmitbutton&quot;]</value>
   </webElementProperties>
</WebElementEntity>
