<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_User not found.</name>
   <tag></tag>
   <elementGuidId>cc8cf043-0641-45ec-9b03-128d7b47eb53</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-summary-errors</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    User not found.
                </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;containerlight&quot;)/div[@class=&quot;fx-containercolumns&quot;]/div[@class=&quot;fx-columnscenter&quot;]/div[@class=&quot;fx-columnright&quot;]/div[@class=&quot;fx-column780full&quot;]/div[@class=&quot;fx-maincontent730&quot;]/div[@class=&quot;fx-columnmaincontent730&quot;]/div[@class=&quot;fx-fullform&quot;]/div[@class=&quot;fx-fullformheader&quot;]/p[@class=&quot;validation-summary-errors&quot;]</value>
   </webElementProperties>
</WebElementEntity>
