<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fx-contactfulladdnotesubmi</name>
   <tag></tag>
   <elementGuidId>8241c4df-e330-4416-8592-88cc19879a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;MainContent_pnlInstructions&quot;)/div[@class=&quot;fx-contactfulladdnotesubmit&quot;]/div[@class=&quot;fx-contactfulladdnotesubmitbutton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fx-contactfulladdnotesubmitbutton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_pnlInstructions&quot;)/div[@class=&quot;fx-contactfulladdnotesubmit&quot;]/div[@class=&quot;fx-contactfulladdnotesubmitbutton&quot;]</value>
   </webElementProperties>
</WebElementEntity>
